// Generated by CoffeeScript 1.3.3
(function() {
  var Prelude;

  Prelude = (function() {

    function Prelude(container, width, height) {
      this.container = container;
      this.width = width;
      this.height = height;
      this.layers = [];
      this.initStage();
      this.initTrack();
      this.status = 'RUNNING';
      this.initEvents();
    }

    Prelude.prototype.initStage = function() {
      this.stage = new Stage(10, this.container, this.width, this.height);
      return this.layers.push(this.stage);
    };

    Prelude.prototype.initTrack = function() {
      var dir, pos;
      dir = {
        x: -1,
        y: 0
      };
      pos = {
        x: 80,
        y: 30
      };
      this.track_z = new Track(this.stage, dir, pos, this.container, this.width, this.height);
      this.track_z.setActions(Actions.Z);
      this.layers.push(this.track_z);
      dir = {
        x: 0,
        y: -1
      };
      pos = {
        x: 20,
        y: 42
      };
      this.track_n = new Track(this.stage, dir, pos, this.container, this.width, this.height);
      this.track_n.setActions(Actions.N);
      this.layers.push(this.track_n);
      dir = {
        x: 0,
        y: -1
      };
      pos = {
        x: 30,
        y: 38
      };
      this.track_a = new Track(this.stage, dir, pos, this.container, this.width, this.height);
      this.track_a.setActions(Actions.A);
      this.layers.push(this.track_a);
      dir = {
        x: 0,
        y: 1
      };
      pos = {
        x: 42,
        y: 10
      };
      this.track_k = new Track(this.stage, dir, pos, this.container, this.width, this.height);
      this.track_k.setActions(Actions.K);
      this.layers.push(this.track_k);
      dir = {
        x: -1,
        y: 0
      };
      pos = {
        x: 80,
        y: 33
      };
      this.track_e = new Track(this.stage, dir, pos, this.container, this.width, this.height);
      this.track_e.setActions(Actions.E);
      return this.layers.push(this.track_e);
    };

    Prelude.prototype.initEvents = function() {
      var _this = this;
      return document.onkeydown = function(event) {
        switch (event.keyCode) {
          case 38:
            return _this.track.turn('UP');
          case 39:
            return _this.track.turn('RIGHT');
          case 40:
            return _this.track.turn('DOWN');
          case 37:
            return _this.track.turn('LEFT');
          case 32:
            return _this.pause();
        }
      };
    };

    Prelude.prototype.run = function() {
      var update,
        _this = this;
      update = function() {
        var i, _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = _this.layers.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          if (!_this.layers[i].update()) {
            _this.layers[i] = _this.layers[_this.layers.length - 1];
            _results.push(_this.layers.pop());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      return this.run_id = setInterval(update, 20);
    };

    Prelude.prototype.stop = function() {
      return clearInterval(this.run_id);
    };

    Prelude.prototype.pause = function() {
      if (this.status === 'RUNNING') {
        this.status = 'STOP';
        return this.stop();
      } else if (this.status === 'STOP') {
        this.status = 'RUNNING';
        return this.run();
      }
    };

    return Prelude;

  })();

  this.Prelude = Prelude;

}).call(this);
