// Generated by CoffeeScript 1.3.3
(function() {
  var Grain,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Grain = (function() {

    function Grain(x, y, size, type, value, context) {
      this.x = x;
      this.y = y;
      this.size = size;
      this.type = type;
      this.value = value;
      this.context = context;
    }

    Grain.prototype.setType = function(type) {
      return this.type = type;
    };

    Grain.prototype.isType = function() {
      var _ref;
      return _ref = this.type, __indexOf.call(arguments, _ref) >= 0;
    };

    Grain.prototype.getWaterColor = function() {
      var blue, green;
      if (this.value > 2) {
        if (this.value > 255) {
          this.value = 255;
        }
        if (this.value < 0) {
          this.value = 0;
        }
        blue = Math.floor(this.value).toString(16);
        if (blue.length === 1) {
          blue += blue;
        }
        green = Math.floor(this.value / 4).toString(16);
        if (green.length === 1) {
          green += green;
        }
        return "#" + green + "00" + blue;
      } else {
        return '#000011';
      }
    };

    Grain.prototype.getMountainColor = function() {
      var brown;
      brown = Math.floor(this.value / 9 * 255).toString(16);
      if (brown.length === 1) {
        brown += brown;
      }
      return "#" + brown + brown + "33";
    };

    Grain.prototype.reset = function() {
      return this.context.clearRect(this.x * this.size + 1, this.y * this.size + 1, this.size - 1, this.size - 1);
    };

    Grain.prototype.render = function(color) {
      switch (this.type) {
        case Type.WATER:
          color = this.getWaterColor();
          break;
        case Type.FOOD:
          color = '#ffff00';
          break;
        case Type.MOUNTAIN:
          color = this.getMountainColor();
      }
      this.context.fillStyle = color;
      return this.context.fillRect(this.x * this.size + 1, this.y * this.size + 1, this.size - 1, this.size - 1);
    };

    return Grain;

  })();

  this.Grain = Grain;

}).call(this);
