// Generated by CoffeeScript 1.3.3
(function() {

  window.onload = function() {
    var prelude,
      _this = this;
    prelude = new Prelude('GameLayer', 800, 600);
    prelude.run();
    return document.onkeydown = function(event) {
      var znake;
      prelude.stop();
      znake = new Game('GameLayer', 800, 600);
      return znake.run();
    };
  };

}).call(this);
