// Generated by CoffeeScript 1.3.3
(function() {
  var NumberBoard,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NumberBoard = (function(_super) {

    __extends(NumberBoard, _super);

    function NumberBoard(container, width, height) {
      NumberBoard.__super__.constructor.apply(this, arguments);
      this.value = 0;
      this.numbers = [];
      this.initNumbers();
    }

    NumberBoard.prototype.initNumbers = function() {
      var digit, _i, _results;
      _results = [];
      for (digit = _i = 0; _i < 3; digit = ++_i) {
        _results.push(this.numbers.push(new Number(digit, 0)));
      }
      return _results;
    };

    NumberBoard.prototype.setNumbers = function() {
      var digit, _i, _results;
      _results = [];
      for (digit = _i = 0; _i < 3; digit = ++_i) {
        _results.push(this.numbers[digit].set(this.value[digit]));
      }
      return _results;
    };

    NumberBoard.prototype.increase = function() {
      this.value++;
      return this.setNumbers();
    };

    return NumberBoard;

  })(Layer);

  this.NumberBoard = NumberBoard;

}).call(this);
