// Generated by CoffeeScript 1.3.3
(function() {
  var Type;

  Type = {
    SNAKE: 'SNAKE',
    GROUND: 'GROUND',
    FOOD: 'FOOD',
    BOUNDARY: 'BOUNDARY'
  };

  this.Type = Type;

}).call(this);
