// Generated by CoffeeScript 1.3.3
(function() {
  var DIGITS, Number;

  DIGITS = ['0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000' + '0000000000'];

  Number = (function() {

    function Number(value) {}

    Number.prototype.set = function(value) {};

    return Number;

  })();

}).call(this);
