// Generated by CoffeeScript 1.3.3
(function() {
  var Utils;

  Utils = {
    random: function(begin, end) {
      return Math.floor(begin + Math.random() * (end - begin));
    },
    randomOne: function() {
      return -1 + Math.random() * 2;
    }
  };

  this.Utils = Utils;

}).call(this);
