// Generated by CoffeeScript 1.3.3
(function() {
  var Brush,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Brush = (function(_super) {

    __extends(Brush, _super);

    function Brush(editor, container, width, height) {
      this.editor = editor;
      Brush.__super__.constructor.call(this, container, width, height);
      this.x;
      this.y;
      this.r = 50;
      this.v = 1;
      this.status = 'UP';
      this.container = $("#" + this.container);
      this.initEvents();
    }

    Brush.prototype.initEvents = function() {
      var _this = this;
      document.onmousemove = function(event) {
        _this.x = event.clientX - _this.container.offset().left;
        _this.y = event.clientY - _this.container.offset().top;
        if (_this.status === 'DOWN') {
          return _this.editor.setGrains(_this.x, _this.y, _this.r, _this.v);
        }
      };
      document.onmousedown = function(event) {
        return _this.status = 'DOWN';
      };
      return document.onmouseup = function(event) {
        return _this.status = 'UP';
      };
    };

    Brush.prototype.shrink = function() {
      if (this.r > 5) {
        return this.r--;
      }
    };

    Brush.prototype.enlarge = function() {
      if (this.r < 100) {
        return this.r++;
      }
    };

    Brush.prototype.update = function() {
      this.context.clearRect(0, 0, this.width, this.height);
      this.context.strokeStyle = '#555555';
      this.context.beginPath();
      this.context.arc(this.x, this.y, this.r, 0, Math.PI * 2, true);
      this.context.closePath();
      return this.context.stroke();
    };

    return Brush;

  })(Layer);

  this.Brush = Brush;

}).call(this);
