// Generated by CoffeeScript 1.3.3
(function() {

  window.onload = function() {
    var mapEditor;
    mapEditor = new MapEditor('MapEditor', 800, 600);
    return mapEditor.run();
  };

}).call(this);
