// Generated by CoffeeScript 1.3.3
(function() {
  var Panel;

  Panel = (function() {

    function Panel(brush) {
      this.brush = brush;
      this.container = $('#panel');
      this.values = $('.heightValue');
      this.initColors();
      this.initEvents();
    }

    Panel.prototype.initColors = function() {
      var getColor, i, value, _i, _len, _ref, _results;
      getColor = function(index) {
        var c;
        c = Math.floor(index / 10 * 255).toString(16);
        if (c.length === 1) {
          c += c;
        }
        return "#" + c + c + "66";
      };
      _ref = this.values;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        value = _ref[i];
        _results.push($(value).css({
          backgroundColor: "" + (getColor(i + 1))
        }));
      }
      return _results;
    };

    Panel.prototype.initEvents = function() {
      var i, value, _i, _len, _ref, _results,
        _this = this;
      _ref = this.values;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        value = _ref[i];
        _results.push($(value).click((function(i) {
          return function() {
            return _this.brush.v = i + 1;
          };
        })(i)));
      }
      return _results;
    };

    return Panel;

  })();

  this.Panel = Panel;

}).call(this);
